language: java
jdk:
- openjdk8
before_install:
  - ip addr list
  - sudo apt-get update -q
  - sudo apt install openjfx libopenjfx-java libopenjfx-jni
script:
- echo BRANCH=$TRAVIS_BRANCH
- echo TAG=$TRAVIS_TAG
- bash ./build.sh
